language: ruby

script: rake test:$RUBY
sudo: false

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - ruby-head

env:
  - RUBY=ruby

matrix:
  include:
  - env: RUBY=mruby[1.3.0]
  - env: RUBY=mruby[master]
  allow_failures:
  - rvm: ruby-head
  - env: RUBY=mruby[master]