language: ruby

script: rake test:$RUBY
sudo: false

rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - ruby-head

env:
  - RUBY=ruby

matrix:
  include:
  - env: RUBY=mruby[1.3.0]
  - env: RUBY=mruby[1.4.0]
  - env: RUBY=mruby[master]
  allow_failures:
  - rvm: ruby-head
  - env: RUBY=mruby[master]